# Generated by Django 3.2.2 on 2021-06-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE', '0003_auto_20210608_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mfModel',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
