# Generated by Django 3.2.2 on 2021-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE', '0005_auto_20210613_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='batteryStatus',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='changedTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='currentPowerSource',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='mfModel',
            field=models.CharField(default='default_mfModel', max_length=32),
            preserve_default=False,
        ),
    ]
