# Generated by Django 3.2.2 on 2021-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IEEE', '0008_auto_20210628_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ess_Qe',
            field=models.FloatField(default=0.0),
        ),
    ]
